name: zip-and-release
on: [ push ]
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Extract datapack version
        run: |
          version=$(awk '/DATAPACK VERSION NUMBER/ { print $5 }' "Brilliance Datapack/data/do2/functions/version.mcfunction")
          echo "BRILLIANCE_VERSION=${version}" >> "$GITHUB_ENV"

      - name: Create zip
        run: cd "Brilliance Datapack" && zip -r brilliance-datapack.zip .

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          make_latest: true
          tag_name: ${{ env.BRILLIANCE_VERSION }}
          files: |
            Brilliance Datapack/brilliance-datapack.zip
            JSON/scoreboards.json
            JSON/items_json/Cards.json
            JSON/items_json/Artifacts.json
            JSON/items_json/Items.json

  trigger-agronet-build:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Trigger Agronet build
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.AGRONET_BUILD_TRIGGER_TOKEN }}" \
               https://api.github.com/repos/trackedout/agronet-fabric/actions/workflows/build.yml/dispatches \
               -d '{"ref":"main"}'
